### ISSUE TITLE
Core dumped when testing lib which uses log4cplus

### ISSUE THREAD

**Issue by SerebryanskiySergei** [log4cplus/log4cplus#391]
**Problem:**
I'm using [Catch2](https://github.com/catchorg/Catch2) test framework and trying to write a simple test for library which uses log4cplus.

The problem is that I'm receiving aborted core dump before any single command in test.cpp file was performed.
For example I've added simple cout << "Hello" in the very beginning, and I don't see that.

I think that the problem is related to log4cplus because I'm able to test the same library with excluded log4cplus, and it works fine. In the same time, my library works with log4cplus integrated when it used by other application, not the unit test, so I've integrated log4cplus into the library correctly.

I've tried to add log4cplus configuration into the test.file, it doesn't help. I'm sure that logger.cfg file in the same location with executable file.

My test.cpp file looks like:
```
#define CATCH_CONFIG_MAIN

#include <catch2/catch.hpp>
#include "ll_api_class.h"

#include <log4cplus/logger.h>
#include <log4cplus/configurator.h>
#include <log4cplus/initializer.h>
#include <log4cplus/loggingmacros.h>

TEST_CASE("CHeck that LL API get_instance works") {

    std::cout << "Hello" << std::endl;

    log4cplus::Initializer initializer;
    std::string config_file = "logger.cfg";
    log4cplus::PropertyConfigurator::doConfigure(config_file);

    // my library calls
    ll_api_class* ll_api;
    ll_api = ll_api_class::get_instance();

    REQUIRE(ll_api != nullptr);
}
```

Result output is:
```
serebro@serebro-OfficePC:~/Apps/10G_Soft/test/unit-tests/bin$ ./LL_API_Unit_tests 
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)

```

When I'm excluding using log4cplus from my library and delete log4cplus-related lines from test, everything works:
test.cpp
```
#define CATCH_CONFIG_MAIN

#include <catch2/catch.hpp>
#include "ll_api_class.h"

// #include <log4cplus/logger.h>
// #include <log4cplus/configurator.h>
// #include <log4cplus/initializer.h>
// #include <log4cplus/loggingmacros.h>

TEST_CASE("CHeck that LL API get_instance works") {

    std::cout << "Hello" << std::endl;

    // log4cplus::Initializer initializer;
    // std::string config_file = "logger.cfg";
    // log4cplus::PropertyConfigurator::doConfigure(config_file);

    // my library calls
    ll_api_class* ll_api;
    ll_api = ll_api_class::get_instance();

    REQUIRE(ll_api != nullptr);
}
```
Result:
```
serebro@serebro-OfficePC:~/Apps/10G_Soft/test/unit-tests/bin$ ./LL_API_Unit_tests 
Hello
===============================================================================
All tests passed (1 assertion in 1 test case)

```

**Extra information**:

 - version: latest
 - operating system, CPU, bitness: Linux, Intel processor with 3.7MHz
 - `configure` script, or CMake, etc., flags and settings: I'm building log4cplus with:
```
   cd $BASEDIR/deps/log4cplus
  ./scripts/fix-timestamps.sh
  rm -rf CMakeCache.txt
  cmake . -DCMAKE_INSTALL_PREFIX:PATH=$STAGING_DIR/log4cplus -DCMAKE_BUILD_TYPE=MinSizeRel
  cmake --build . --target install --clean-first
```
 - flags and settings used by your application: in my CMake configuration for my application I have the following settings:
```
set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_POSITION_INDEPENDENT_CODE ON)
set(CMAKE_INSTALL_RPATH_USE_LINK_PATH TRUE)
set(BUILD_SHARED_LIBS ON)
set(CMAKE_FIND_STATIC LAST)
```
 - compiler and its version: 
```
serebro@serebro-OfficePC:~/Apps/10G_Soft/test/unit-tests/bin$ c++ -v
Using built-in specs.
COLLECT_GCC=c++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.5.0-12ubuntu1' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 5.5.0 20171010 (Ubuntu 5.5.0-12ubuntu1) 
serebro@serebro-OfficePC:~/Apps/10G_Soft/test/unit-tests/bin$ cc -v
Using built-in specs.
COLLECT_GCC=cc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.5.0-12ubuntu1' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 5.5.0 20171010 (Ubuntu 5.5.0-12ubuntu1) 
serebro@serebro-OfficePC:~/Apps/10G_Soft/test/unit-tests/bin$ 
```

**Comment by SerebryanskiySergei** [comment]
I've tried to repeat the same thing with other testing framework - GoogleTest, and there I have segfault when I'm using log4cplus library.

**Comment by wilx** [comment]
Put the log4cplus::Initializer instance in `main()`.

**Comment by SerebryanskiySergei** [comment]
I don't have main() in the Catch file.
I've attached test.cpp file in the very top.

**Comment by wilx** [comment]
If you are using `main()` provided by the Catch2 framework then you can replace it with your own that does the initialization. See https://github.com/catchorg/Catch2/blob/master/docs/own-main.md.

**Comment by SerebryanskiySergei** [comment]
Hi @wilx !
I've tried to do that, but I had the same result.
test.cpp: 
```
#define CATCH_CONFIG_RUNNER
#include <catch2/catch.hpp>

#include "ll_api_class.h"
#include <log4cplus/initializer.h>

int main( int argc, char* argv[] ) {
    log4cplus::Initializer initializer;
    int result = Catch::Session().run( argc, argv );
    return result;
}

TEST_CASE("CHeck that LL API get_instance works") {
    ll_api_class* ll_api;
    ll_api = ll_api_class::get_instance();

    REQUIRE(ll_api != nullptr);
}
```

**Comment by SerebryanskiySergei** [comment]
I thought that it might be problem somewhere deep un Ctach2 framework, so I've moved to Google Test framework completely.
Here I have well defined main function:
```
int main(int argc, char **argv) {
#ifdef LOG4CPLUS
    log4cplus::Initializer initializer;
    log4cplus::BasicConfigurator config;
    config.configure();
#endif
    ::testing::InitGoogleTest(&argc, argv);
    return RUN_ALL_TESTS();
}
```
As a result with Google Test I have crash not on the early start, but when the library exactly is trying to log smthg using log4clus:
```
--------------------------------------------------------------------------------
-------------------------- STAR LL API UNIT TESTS... ---------------------------
--------------------------------------------------------------------------------
[==========] Running 7 tests from 2 test suites.
[----------] Global test environment set-up.
[----------] 2 tests from LL_API_creation_test
[ RUN      ] LL_API_creation_test.Call_get_instance
[       OK ] LL_API_creation_test.Call_get_instance (0 ms)
[ RUN      ] LL_API_creation_test.Call_init_system_bringup_params
[       OK ] LL_API_creation_test.Call_init_system_bringup_params (1 ms)
[----------] 2 tests from LL_API_creation_test (1 ms total)

[----------] 5 tests from LowLevelAPITest
[ RUN      ] LowLevelAPITest.init_all
./run.sh: line 145: 10529 Segmentation fault      (core dumped) ./init_ll_api
```
I have a special function for debugging, where I can switch between log4clus and regular printf:
```
void debug_log(const char *format, ...) {
   va_list args;
   va_start (args, format);
#ifdef LOG4CPLUS
   log4cplus::Logger logger;

   if (logger_p == nullptr)
      *logger_p= log4cplus::Logger::getInstance(LOG4CPLUS_TEXT("lowLogger"));

   logger = *logger_p;      // This is already a pointer

   char buffer [DEBUG_LOG_BUF_SIZE];
   vsnprintf(buffer, DEBUG_LOG_BUF_SIZE, format, args);
   LOG4CPLUS_CALLTRACE(logger, buffer);
#else
   FILE *log_fh = fopen ("debug_ptp.log", "w");
   vfprintf (stdout, format, args );
   fclose (log_fh);
#endif       // LOG4CPLUS
   va_end (args);
} 
```
When I'm switching to the printfs, everything works correct. When log4cplus is in use, I have the segment fault.
Back trace:
```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff789400e in log4cplus::Logger::swap(log4cplus::Logger&) () from /home/serebro/UnitTests/build/staging/log4cplus/lib64/liblog4cplus.so.0
Missing separate debuginfos, use: debuginfo-install glibc-2.17-157.el7.x86_64 libgcc-4.8.5-36.el7.x86_64 libstdc++-4.8.5-36.el7.x86_64
(gdb) bt
#0  0x00007ffff789400e in log4cplus::Logger::swap(log4cplus::Logger&) () from /home/serebro/UnitTests/build/staging/log4cplus/lib64/liblog4cplus.so.0
#1  0x00007ffff7894066 in log4cplus::Logger::operator=(log4cplus::Logger&&) () from /home/serebro/UnitTests/build/staging/log4cplus/lib64/liblog4cplus.so.0
#2  0x00007ffff7b3fd80 in debug_log (format=0x7ffff7bb032c "%s %s 0x%x\n") at /home/serebro/UnitTests/src/ll_software/low_level_api/src/ll_utils.cpp:62
#3  0x00007ffff7b4a97e in pio_class::init(std::function<int (unsigned int, unsigned int*)>, std::function<int (unsigned int, unsigned int)>, unsigned int) (this=0x6fc1e0, rd=..., wr=..., base=7340032)
    at /home/serebro/UnitTests/src/ll_software/low_level_api/src/pio_class.cpp:71
#4  0x00007ffff7b3597d in ll_api_class::init_all (this=0x6fbf70) at /home/serebro/UnitTests/src/ll_software/low_level_api/src/ll_api_class.cpp:201
#5  0x000000000047d3ed in LowLevelAPITest_init_all_Test::TestBody (this=0x7058b0) at /home/serebro/UnitTests/test/unit-tests/ll_api/test.cpp:117
#6  0x00000000004b7665 in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) ()
#7  0x00000000004b1580 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) ()
#8  0x00000000004913a8 in testing::Test::Run() ()
#9  0x0000000000491c01 in testing::TestInfo::Run() ()
#10 0x0000000000492269 in testing::TestSuite::Run() ()
#11 0x000000000049ca27 in testing::internal::UnitTestImpl::RunAllTests() ()
#12 0x00000000004b854b in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) ()
#13 0x00000000004b256c in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) ()
#14 0x000000000049b619 in testing::UnitTest::Run() ()
#15 0x000000000047e8ee in RUN_ALL_TESTS () at /home/serebro/UnitTests/build/staging/googletest/include/gtest/gtest.h:2469
#16 0x000000000047da57 in main (argc=1, argv=0x7fffffffe318) at /home/serebro/UnitTests/test/unit-tests/ll_api/test.cpp:150
```

**Comment by SerebryanskiySergei** [comment]
The problem was in reassigning logger pointer: 
```
if (logger_p == nullptr)
      *logger_p= log4cplus::Logger::getInstance(LOG4CPLUS_TEXT("lowLogger"));
logger = *logger_p;      // This is already a pointer
```
