### ISSUE TITLE
ThreadPool::~ThreadPool() Windows Deadlock Posible Solution

### ISSUE THREAD

**Issue by sldr** [log4cplus/log4cplus#408]
The ThreadPool destructor will still deadlock when
log4cplus::Initializer initializer;
is at top of main if main starts a thread and in that thread exit(2); is called.

The following will fix the issue and doesn't require log4cplus::Initializer initializer; in main.
 - version: 2.0.4
 - operating system, CPU, bitness: Windows 10 Enterprise 1809 17763.437, Intel Xeon E5-2670 0 @ 2.60GHz (2 processors), x64
 - `configure` script, or CMake, etc., flags and settings: VS 2017 15.9.11 built using:
msbuild /nologo /m /nr:false /p:"Platform=x64" /p:Configuration=Release /t:log4cplus ".\log4cplus\msvc14\log4cplus.sln"
Note: updated projects to 8.1 and 141 using VS 2017 GUI first

What is happening is that the threadpool threads are not going thru normal run down during exit(…) call so the workers vector isn't empty when the condition_consumers condition is signaled so the predicate check fails. I modified the predicate check to go thru the workers and check if they still exist. If none exist I have to detach() the threads otherwise thread destructor throws when it tries to join a thread. Hope this helps!

SLDR
(Stephen L. De Rudder)

Here is the new ThreadPool destructor:
```C++
inline ThreadPool::~ThreadPool()
{
    std::unique_lock<std::mutex> lock(queue_mutex);
    stop = true;
    condition_consumers.notify_all();
    condition_producers.notify_all();
    pool_size = 0;
    condition_consumers.wait(lock,
      [this]
    {
      //return this->workers.empty();
      if (this->workers.empty()) {
        return true;
      } else {
#if defined (_WIN32)
        for (std::vector< std::thread >::reverse_iterator i = this->workers.rbegin(); i < this->workers.rend(); ++i) {
          HANDLE hThread = i->native_handle();
          if (WaitForSingleObject(hThread, 0) != WAIT_OBJECT_0) {
            return false;
          }
        }
        for (std::vector< std::thread >::reverse_iterator i = this->workers.rbegin(); i < this->workers.rend(); ++i) {
          i->detach();
        }
        return true;
#else
        return false;
#endif
      }
    });
    assert(in_flight == 0);
}
```

**Comment by wilx** [comment]
My gut feeling is to say "Don't do that." I will have to think about this.

**Comment by wilx** [comment]
What about solving this on your side like this: Register a handler with [`std::atexit()`](https://en.cppreference.com/w/cpp/utility/program/atexit) to call `log4cplus::deinitialize()` which should shut down things properly.

**Comment by wilx** [comment]
What about solving this on your side like this: Register a handler with [`std::atexit()`](https://en.cppreference.com/w/cpp/utility/program/atexit) to call `log4cplus::deinitialize()` which should shut down things properly.

**Comment by kostrom** [comment]
I have the same issue with log4cplus::deinitialize() hanging during shutdown of a python extension (which is just a dll) on windows. This code change fixes it for me.

**Comment by kaijibis** [comment]
lib deinit hangs for applications running in the background. how should the lib be initialized for such cases? it looks like it is waiting for threads that probably got lost in [daemon](https://man7.org/linux/man-pages/man3/daemon.3.html). regardless of whether initialiter code is called before or after the daemon

```c++
(gdb) info threads
  Id   Target Id                                 Frame 
* 1    Thread 0x7ff9b83749c0 (LWP 39017) "sieve" 0x00007ff9b71bfa0e in __futex_abstimed_wait_common64 (
    private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x563cb35095d4)
    at ./nptl/futex-internal.c:57

(gdb) bt
#0  0x00007ff9b71bfa0e in __futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, 
    expected=0, futex_word=0x563cb35095d4) at ./nptl/futex-internal.c:57
#1  __futex_abstimed_wait_common (futex_word=futex_word@entry=0x563cb35095d4, 
    expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, 
    private=private@entry=0, cancel=cancel@entry=true) at ./nptl/futex-internal.c:87
#2  0x00007ff9b71bfa8b in __GI___futex_abstimed_wait_cancelable64 (
    futex_word=futex_word@entry=0x563cb35095d4, expected=expected@entry=0, clockid=clockid@entry=0, 
    abstime=abstime@entry=0x0, private=private@entry=0) at ./nptl/futex-internal.c:139
#3  0x00007ff9b71c2170 in __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x563cb3509550, 
    cond=0x563cb35095a8) at ./nptl/pthread_cond_wait.c:503
#4  ___pthread_cond_wait (cond=0x563cb35095a8, mutex=0x563cb3509550) at ./nptl/pthread_cond_wait.c:618
#5  0x00007ff9b789d96b in std::condition_variable::wait<progschj::ThreadPool::~ThreadPool()::{lambda()#1}>(std::unique_lock<std::mutex>&, progschj::ThreadPool::~ThreadPool()::{lambda()#1}) (__p=..., 
    __lock=..., this=0x563cb35095a8) at /usr/include/c++/13/condition_variable:105
#6  progschj::ThreadPool::~ThreadPool (this=0x563cb35094d0, __in_chrg=<optimized out>)
    at ./threadpool/ThreadPool.h:176
#7  std::default_delete<progschj::ThreadPool>::operator() (this=<optimized out>, __ptr=0x563cb35094d0)
    at /usr/include/c++/13/bits/unique_ptr.h:99
#8  std::default_delete<progschj::ThreadPool>::operator() (__ptr=0x563cb35094d0, this=<optimized out>)
    at /usr/include/c++/13/bits/unique_ptr.h:93
#9  std::__uniq_ptr_impl<progschj::ThreadPool, std::default_delete<progschj::ThreadPool> >::reset (
    __p=0x0, this=<optimized out>) at /usr/include/c++/13/bits/unique_ptr.h:211
#10 std::unique_ptr<progschj::ThreadPool, std::default_delete<progschj::ThreadPool> >::reset (__p=0x0, 
    this=<optimized out>) at /usr/include/c++/13/bits/unique_ptr.h:509
#11 log4cplus::shutdownThreadPool () at ./src/global-init.cxx:339
#12 0x00007ff9b789da8d in log4cplus::deinitialize () at ./src/global-init.cxx:560
#13 0x00007ff9b789dae5 in log4cplus::Initializer::~Initializer (this=<optimized out>, 
    __in_chrg=<optimized out>) at ./src/global-init.cxx:120
```
